- project:
    check:
      jobs:
        - monasca-tempest-python-influxdb
        - monasca-tempest-python-cassandra
        - monascalog-tempest
    gate:
      jobs:
        - monasca-tempest-python-influxdb
        - monasca-tempest-python-cassandra
        - monascalog-tempest